apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
spec:
    generators:
    - list:
        elements:
        - env: dev
        - env: prd
    template:
        metadata:
            name: 'my-app-{{.env}}'
        spec:
            project: 'my-app-{{.env}}'
            source:
                repoURL: "https://github.com/nabdali/argocd-labs.git"
                path: '{{.env}}/'
            destination:
                server: 'https://kubernetes.default.svc'
                namespace: argocd