apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
spec:
    generators:
    - list:
        elements:
        - env: dev
        - env: prd
    template:
        metadata:
            name: 'my-app-{{.env}}'
        spec:
            source:
                repoURL: "https://github.com/myorg/myapp"
                path: '{{.env}}/'
            destination:
                server: 'cluster-{{.env}}'
                namespace: my-app