apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: guestbook
spec:
  project: default

  source:
    repoURL: https://github.com/nabdali/argocd-labs.git
    targetRevision: HEAD
    path: workshop-2 # git only
    directory:
      recurse: true
      exclude: 'config.yaml'
      include: 'deployment.yaml'
  destination:
    server: https://kubernetes.default.svc
    name: my-kube-cluster
    namespace: guestbook

  # Extra information to show in the Argo CD Application details tab
  info:
    - name: 'Example:'
      value: 'https://example.com'

  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
    prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
    selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).